### ISSUE TITLE
failed to compile with nightly rust

### ISSUE THREAD

**Issue by dragancc** [harharkh/mayda#1]
Hey, I'm very interested in using mayda, but it fails to build with nightly rust (more details bellow), are you still developing it? 

```
cargo build             
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling mFail to buildayda_macros v0.1.3
error[E0425]: unresolved name `token::str_to_ident`
   --> /home/dnc/.cargo/registry/src/github.com-1ecc6299db9ec823/mayda_macros-0.1.3/src/lib.rs:169:12
    |
169 |   let ut = token::str_to_ident(&*format!("u{}", width));
    |            ^^^^^^^^^^^^^^^^^^^ unresolved name

error[E0425]: unresolved name `token::str_to_ident`
   --> /home/dnc/.cargo/registry/src/github.com-1ecc6299db9ec823/mayda_macros-0.1.3/src/lib.rs:182:19
    |
182 |       let ident = token::str_to_ident(&*name);
    |                   ^^^^^^^^^^^^^^^^^^^ unresolved name

error[E0425]: unresolved name `token::str_to_ident`
   --> /home/dnc/.cargo/registry/src/github.com-1ecc6299db9ec823/mayda_macros-0.1.3/src/lib.rs:279:15
    |
```

**Comment by harharkh** [comment]
Hello Dragan,

No, not at the moment. There was massive breakage when the update to MIR 
happened, and I resolved to wait until the compiler plugin situation 
stabilized some to put everything back in order.

What is the timeline for your project?

Jeremy

**Comment by dragancc** [comment]
Hi Jeremy, 
 I need an integer compression in a project I'm working on (nearest neighbors for a big data sets, >=1billion entries) and your project was the only one I've found. No particular time-line, but would like to try it at some point, rather sooner than later. :) 
best, 
Dragan 
EDIT: btw if it make sense to put some work into fixing compilation issues now, I could maybe help out a bit.

**Comment by harharkh** [comment]
Hello Dragan,

Alright, then I will move this up the priority list. Unfortunately I am 
between jobs right now, and the soonest I will probably be able to come 
back to this is the middle of January.

Once I start making progress though I will try to let you know.

Regards,

Jeremy

**Comment by 0xDeva** [comment]
Hello harharkh,

Thanks for your awesome work.
I'm also very interested in using mayda. Are there any Rust alternative, waiting that the errors are fixed ?
regards

**Comment by harharkh** [comment]
Hello Guillaume,

No, I don't know of any alternative. My apologies that I have not kept 
up with the breakage, but working with compiler plugins is so difficult 
right now that I thought I would wait for the language to stabilize some 
more.

Hopefully I will get back to this in January though.

Regards,

Jeremy

**Comment by slde-flash** [comment]
any news?

**Comment by harharkh** [comment]
No, unfortunately. I think that I am going to abandon this project until the compiler plugin story stabilizes. If there is enough interest though, I would be happy transferring ownership.

**Comment by dragancc** [comment]
@harharkh I'd try to fix this specific issue if you  think you would have some time to review ?

**Comment by harharkh** [comment]
Yes, of course I would. You may need to spend some time looking at the internals of libsyntax to get the syntax extensions to compile though.

**Comment by harharkh** [comment]
After the patch by Francis and an update to the dependency versions, mayda compiles on nightly. For reproducibility, a specific version of the nightly compiler has been specified in `./rust-toolchain`. You should be able to change this to `nightly` and still get the code to compile, at least until the next overhaul of compiler internals.

**Comment by dragancc** [comment]
Great! Thanks! Will give it a try!
